### ISSUE TITLE
nuke12 兼容性报错

### ISSUE THREAD

**Issue by nervYu** [weijer/NukeToolSet#10]
加载后提示
AttributeError: 'module' object has no attribute 'QStringListModel

**Comment by TonyShu1218** [comment]
Same issue here

**Comment by polestarclark** [comment]
同求

**Comment by ReimuSG** [comment]
> 加载后提示
> AttributeError: 'module' object has no attribute 'QStringListModel

去下面的地址更新一下Qt.py就好了..替换一下原来那个
https://github.com/mottosso/Qt.py

**Comment by mightyang** [comment]
也可以暴力点，打开 Qt.py，找到QStringListModel，直接把 pyside2 里的 QStringListModel 这一行给屏蔽掉就可以打开了。

**Comment by weijer** [comment]
#11
