### ISSUE TITLE
nuke13下 cryptomatte 与nuke13自带的冲突

### ISSUE THREAD

**Issue by parkingsir** [weijer/NukeToolSet#16]
大佬你好 在您的插件包里cryptomatte与nuke13自带的有冲突  如果不用您的插件包 read节点就不显示帧范围了

**Comment by weijer** [comment]
https://github.com/weijer/NukeToolSet/commit/0233f94b858d8dd588d8d1d487f18649945fa8a4

修复了，等我发个新版本

**Comment by parkingsir** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
