### ISSUE TITLE
NukeX 13.2v1中使用read节点名出现乱码，大佬有办法解决吗？

### ISSUE THREAD

**Issue by jonmolim** [weijer/NukeToolSet#20]
NukeX 13.2v1中使用read节点名出现乱码，大佬有办法解决吗？在节点修改字体就能正常显示，但是每次都需要选下字体也很麻烦。

**Comment by jonmolim** [comment]
暂时是先把 run.knob_show_frame()给注释掉了，等有解决办法再改回来

**Comment by weijer** [comment]
没发现这个问题哈
