### ISSUE TITLE
插件内自带cryptomatte工具和原生工具有冲突

### ISSUE THREAD

**Issue by ABnerccc** [weijer/NukeToolSet#9]
nuke11之下，cryptomatte节点不能正常使用。加载了 tool时，tool内自带的cryptomatte和原生的节点都会出现问题。不加载tool后。原生节点使用就会正常。

**Comment by weijer** [comment]
好的 我看一下

**Comment by weijer** [comment]
https://github.com/weijer/NukeToolSet/commit/0233f94b858d8dd588d8d1d487f18649945fa8a4
